BASE <http://dx.doi.org/>
PREFIX cito: <http://purl.org/spar/cito/>
#PREFIX dcterms: <http://purl.org/dc/terms/>
#PREFIX datacite: <http://purl.org/spar/datacite/>
#PREFIX literal: <http://www.essepuntato.it/2010/06/literalreification/>
#PREFIX biro: <http://purl.org/spar/biro/>
#PREFIX frbr: <http://purl.org/vocab/frbr/core#>
#PREFIX c4o: <http://purl.org/spar/c4o/>
SELECT *
WHERE {
  ?citation cito:hasCitedEntity <10.1016/j.mrgentox.2011.04.011> .
  OPTIONAL {
    ?s ?op ?citation .
  }
  OPTIONAL {
    ?citation ?sp ?o .
  }
}
