WHENEVER SQLERROR EXIT FAILURE
SET ECHO ON
SET SERVEROUTPUT ON

DROP TABLE tmp_appls;

/*CREATE TABLE tmp_appls
  AS
    SELECT *
    FROM appls WITH NO DATA;*/

/*
CREATE TABLE tmp_appls(LIKE appls INCLUDING ALL);*/

CREATE TABLE tmp_appls AS
  SELECT *
  FROM appls
  FETCH FIRST 0 ROWS ONLY;

EXIT